# Generated by Django 4.2.2 on 2023-07-13 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('fechaCompra', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('usuario', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('problema', models.CharField(max_length=50, verbose_name='Problema')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen2')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productos.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
